version: "4.4.1"
services:
    db:
        container_name: db
        image: mysql:8.0
        environment:
            MYSQL_ROOT_PASSWORD: ${DB_PASSWORD-root}
            MYSQL_DATABASE: ${DB_DATABASE-basecommerce}
            MYSQL_USER: ${DB_USERNAME-basecommerce}
            MYSQL_PASSWORD: ${DB_PASSWORD-basecommerce}
            MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
            MYSQL_AUTHENTICATION_PLUGIN: mysql_native_password
        volumes:
            - ./volumes/database/:/var/lib/mysql:rw
            - ./mysql:/etc/mysql/conf.d
            - ./mysql:/etc/mysql/my.cnf
        healthcheck:
            test: [ "CMD", "localhost", "mysqladmin" ,"ping", "-h" ]
            timeout: 100s
            retries: 10
        ports:
            - ${DATABASE_PORT:-3307}:3306
#    phpmyadmin:
#        image: phpmyadmin/phpmyadmin
#        ports:
#            - '8080:80'
#        restart: always
#        environment:
#            PMA_HOST: db
#        depends_on:
#            - db
    system:
        container_name: system
        image: system:dev
        build:
            context: .
            dockerfile: system/Dockerfile_dev
            network: host
            args:
                app_env: dev
        env_file: system/.env.local
        working_dir: /opt/www
        volumes:
            - ./system/:/opt/www
        ports:
            - "91:8000"
        networks:
            - default
networks:
    default:
