FROM php:8.1.1-fpm-alpine3.14
LABEL version="1.0" license="MIT" maintainer="Manoj Malakar <manoj@squarebx.com>" app.name="GadgetByte Base Image"

ARG timezone
ARG COMPOSER_VERSION=2.5.8

ENV TIMEZONE=${timezone:-"Asia/Kathmandu"}

#setup php extension
RUN apk add --no-cache \
      zip libzip-dev \
      gmp-dev  \
    && docker-php-ext-install gmp zip mysqli pdo_mysql

#Setup nginx git supervisor composer
RUN apk add --no-cache nginx bash git supervisor \
    && mkdir -p /etc/supervisor.d/ \
    && wget -nv -O /usr/local/bin/composer https://github.com/composer/composer/releases/download/${COMPOSER_VERSION}/composer.phar \
    && chmod u+x /usr/local/bin/composer


#setup timezone
RUN apk add tzdata \
    && cd /usr/local/etc/php \
    # - config PHP
    && { \
        echo "upload_max_filesize=100M"; \
        echo "memory_limit=1024M"; \
        echo "post_max_size=100M";\
        echo "date.timezone=${TIMEZONE}"; \
    } | tee conf.d/99_overrides.ini \
    && ln -sf /usr/share/zoneinfo/${TIMEZONE} /etc/localtime \
    && echo "${TIMEZONE}" > /etc/timezone

# check php version
RUN php -v \
    && php -m \
    && rm -rf /var/cache/apk/* /tmp/* /usr/share/man \
    && docker-php-source delete \
    #&& apk del .build-deps \
    && echo -e "\033[42;37m Build Completed :).\033[0m\n"

RUN addgroup -g 1000 -S gbn
RUN adduser -u 1000 -S -G gbn gbn

# Configure php-fpm & nginx
RUN mkdir -p /run/php/ \
    && touch /run/php/php-fpm.sock \
    && mkdir -p /run/nginx/ \
    && touch /run/nginx/nginx.pid \
    && ln -sf /dev/stdout /var/log/nginx/access.log \
    && ln -sf /dev/stderr /var/log/nginx/error.log \
    && rm /usr/local/etc/php-fpm.d/zz-docker.conf \
    && chown -Rf gbn:gbn \
    /run/nginx/nginx.pid \
    /var/log/nginx \
    /var/lib/nginx \
    /run/php \
    && chmod g+wx /var/log/

#RUN apt clean

COPY system/.docker/fpm/php-fpm.conf /usr/local/etc/php-fpm.conf
COPY system/.docker/fpm/www.conf /usr/local/etc/php-fpm.d/www.conf
COPY system/.docker/fpm/fastcgi-php.conf /etc/nginx/fastcgi-php.conf
COPY system/.docker/supervisord.ini /etc/supervisor.d/supervisord.ini
COPY system/.docker/nginx/nginx.conf /etc/nginx/nginx.conf
COPY system/.docker/nginx/default.conf /etc/nginx/http.d/default.conf

WORKDIR /opt/www/

COPY system/startdev.sh .
# cleanup
RUN #rm -rf system/storage/var/cache/apk/* /tmp/* /usr/share/man

RUN chown -Rf gbn:gbn /opt/www \
    && chmod +x startdev.sh
USER gbn

EXPOSE 8000
CMD ["sh", "startdev.sh"]
